MeRestaurant/MeRestaurantProj/MeRestaurantProj/Controllers/MenuController.cs
using MeRestaurantProj.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeRestaurantProj.Controllers
{
    public class MenuController : Controller
    {
        private readonly ApplicationContext _context;

        public MenuController(ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> AddDish([Bind("Name, Price")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dish);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dish);
        }
    }
}

MeRestaurant/MeRestaurantProj/MeRestaurantProj/Controllers/OrderController.cs
using MeRestaurantProj.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeRestaurantProj.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationContext _context;

        public OrderController(ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult AddToBucket([Bind("Name,Price")] Dish dish)
        {
            _context.Orders.Add(new Order { Dishes = { dish } });
            return RedirectToAction("Index");
        }
    }
}

MeRestaurant/MeRestaurantProj/MeRestaurantProj/Views/Menu/AddDish.cshtml
@model MeRestaurantProj.Models.Dish

@{
    ViewData["Title"] = "Login";
}

<div class="text-center">
    <h2>Enter the Dish</h2>
    <a asp-action="AddDish" asp-controller="Menu">AddDish</a>

    <form asp-action="AddDish" asp-controller="Menu" asp-anti-forgery="true">
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div>
            <div class="form-group">
                <label asp-for="Name">Enter Name:</label><br />
                <input type="text" asp-for="Name" />
                <span asp-validation-for="Name" />
            </div>
            <div class="form-group">
                <label asp-for="Price">Enter Price:</label><br />
                <input asp-for="Price" />
                <span asp-validation-for="Price" />
            </div>
            <div class="form-group">
                <input type="submit" value="Add a dish" />
            </div>
        </div>
    </form>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

MeRestaurant/MeRestaurantProj/MeRestaurantProj/Views/Menu/Index.cshtml
@model MeRestaurantProj.Models.ApplicationContext;

@{
    ViewData["Title"] = "Index";
}

<h1>Movies</h1>

<p>
    @if (User.IsInRole("admin"))
    {
        <a asp-action="AddDish">Add a Dish</a>
    }
</p>

<table class="table">
    <tbody>
        @foreach (var item in Model.Dishes)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <a asp-action="AddToBucket" asp-controller="Order" asp-route-id="@item.Id">Add To bucket</a>
                    @if (User.IsInRole("admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>